global using OrcaIzi.Application.DTOs;
global using OrcaIzi.Application.Interfaces;
global using OrcaIzi.Domain.Entities;
global using OrcaIzi.Domain.Interfaces;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
